name: Build on macOS

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: brew install autoconf automake libtool && \
          ./build.sh
