name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matric.os }}
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
        os: ['macos-10.15', 'ubuntu-20.04']
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: brew install automake
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install setuptools wheel twine
      - name: Build
        run: ./build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: dist
          name: ${{ matrix.python-version }}-artifact
          retention-days: 5
      - name: Publish
        env:
          TWINE_REPOSITORY_URL: https://pypi.python.org/pypi
          TWINE_NON_INTERACTIVE: 1
        run: twine upload dist/*
